Repository betagouv/anssi-demain-specialiste-cyber, pull requests merged in 2025-09, with the labels that each got.

#66 [SOIN] Sépare les styles
  back/vues/entete.pug
  back/vues/pied-de-page.pug
  front/src/_encart-chiffres-cles.scss
  front/src/_encart-cyberenjeux.scss
  front/src/_encart-intro.scss
  front/src/_encart-selections.scss
  front/src/_encart-soutiens.scss
  front/src/_entete.scss
  front/src/_fonts.scss
  front/src/_global.scss
  front/src/_pied-de-page.scss
  front/src/_standard.scss
  front/src/index.scss
Labels: enhancement

#69 Affiche le menu en mode bureau
  back/vues/entete.pug
  front/src/_entete.scss
  front/src/_points-de-rupture.scss
Labels: enhancement

#70 [TECH] Modifie la configuration eslint
  .pre-commit-config.yaml
Labels: bug, enhancement

#86 Corrige le moteur de rendu et améliore l'enregistrement des routes
  back/src/api/dsc.ts
  back/src/api/moteurDeRendu.ts
  back/src/api/ressourcesApi.ts
  back/src/api/ressourcesOidc.ts
  back/src/api/ressourcesPages.ts
  back/tests/api/dsc.spec.ts
Labels: bug

#105 [CORRECTION] Corrige l’action github pour le déploiement
  .github/workflows/deploiement.yml
Labels: bug

#108 [BUG] Corrige la lecture des jeux
  back/src/infra/entrepotJeuxPostgres.ts
Labels: bug

#125 Corrige la disparition du placeholder
  front/src/jeux/FormulaireNouveauJeu/EtapeInformationsGenerales.svelte
  front/src/jeux/FormulaireNouveauJeu/EtapePresentation.svelte
Labels: enhancement

#123 Mets à jour vite 7
  front/package.json
  front/tests/vitest-setup.ts
  package-lock.json
Labels: dependencies

#122 Mets à jour les disciplines
  back/src/metier/referentiels/disciplines.ts
  front/src/jeux/FormulaireNouveauJeu/EtapeInformationsGenerales.svelte
Labels: enhancement

#130 Mets à jour l'UI Kit en version 1.28.0
  back/vues/base.pug
  front/package.json
  package-lock.json
Labels: dependencies
